@localhost =  http://localhost:5000



### Create Movement
POST {{localhost}}/movements
Content-Type: application/json

{
   "movementName": "Pushup5",
   "movementDisplayName": "Pushup5",
   "videoUrl": "http://www.google5.com",
   "videoStartTime": 5.55,
   "videoEndTime": 5.5,
   "videoSource": "Youtube5",
   "equipmentList": ["Pushup5"],
   "workoutCategoryList": ["Strength5"]
}

#### Get All Movements
GET {{localhost}}/movements


### Get a specific movement by movementId
GET {{localhost}}/movements/616046ad321605b19aa89197


###